### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by eshaank1** [eshaank1/csp#1]
- [ ] JS Output
- [ ] Calculator
- [ ] Python tricks
- [ ] Docs already in time box
- [ ] Make weekly tangibles and plans
- [ ] Make quiz
- [ ] Re-make picture dark background
- [ ] Add style to bottom everywhere
- [ ] Figure out customization
- [ ] Fix zoomed in not showing sidebars on other monitors
- [ ] Fix spacing and format on all pages
- [ ] Test and get favicon
- [ ] Add logo for home header
- [ ] Add github profile link as picture on the right side of the header
- [ ] Catchup on all slack messages
- [ ] Finish live review 2 prep
- [ ] Finish live review 3 prep on slack todolist link
- [ ] Add issues todolist to tangibles
- [ ] Fix formatting on all resolutions
- [ ] Fix formatting on time box tables and words
